--- #how a YAML file (and a Playbook start)
- name: gather interfaces resource # this is the Playbook
  hosts: all	# host definition baed on invntory. Against which host or group the playbook will run
  gather_facts: false # Facts Gathering. Fon Network is usually set to False because there are specific modules for it
  connection: local      # Type of Ansible Connection: local, network_cli, netconf, httpapi

  vars_files:         # include external variable files
    - credentials.yml
  vars:            # define playbook variables
    cli:           # dict that define the variables used by the provider of the connection: 
      username: '{{username}}'
      password: '{{password}}'
      host: '{{ansible_host}}'
      auth_pass: '{{password}}'
      authorize: yes
  tasks:                    # Task list. Always run from Top to Bottom
    - name: Gather L2 interfaces resource facts # Task name
      ios_facts:                # Module https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_facts_module.html
        provider: '{{ cli }}'
        gather_network_resources: l2_interfaces
      register: l2_if              # Ansible registers are used when you want to capture the output of a task to a variable 
    - debug:                  # Module https://docs.ansible.com/ansible/latest/collections/ansible/builtin/debug_module.html
        var: l2_if               # The variable we want to print